- components/TheFooter.vue
- components/TheHeader.vue
- layouts/default.vue
> Issue 04 - Adiciona Footer

- pages/__tests__/__snapshots__/solicitacao.test.js.snap
- pages/__tests__/solicitacao.test.js
- pages/solicitacao.vue
closes #6 
Foi criado o esqueleto da página de solicitação. O click no botão simula sucesso para exibir o alert.
Lista de screenshots:
<details>
<summary>Desktop</summary>
</details>
<details>
<summary>Mobile</summary>
</details>
<details>
<summary>Vídeos</summary>
[Gravação de tela de 21-09-2022 22:09:10.webm](https://user-images.githubusercontent.com/32873281/191641398-9226d3d6-f6c6-4e40-9d50-e5bd4faabff0.webm)
[Gravação de tela de 21-09-2022 22:09:38.webm](https://user-images.githubusercontent.com/32873281/191641401-6a766ec7-ed64-492b-b959-70d6afe2408e.webm)
</details>
> Issue 06 - Página de solitação/report

- layouts/login.vue
- pages/__tests__/__snapshots__/admin.test.js.snap
- pages/__tests__/admin.test.js
- pages/admin.vue
closes #23 
<details>
<summary>Desktop</summary>
</details>
<details>
<summary>Mobile</summary>
</details>
> [Issue 23] - Página de login do Admin

- components/admin/AdminChart.vue
- pages/admin/__tests__/__snapshots__/ranking-linhas.test.js.snap
- pages/admin/__tests__/acessos-diarios.test.js
- pages/admin/__tests__/ranking-linhas.test.js
- pages/admin/acessos-diarios.vue
- pages/admin/ranking-linhas.vue
Foi criado o esqueleto da página de ranking de linhas: https://www.figma.com/file/J0JSVXtYko6Fo4ePydHJ0t/EMTU?node-id=774%3A3202
> [Issue 28] - Página de Ranking de linhas

- jest.config.js
- pages/admin/__tests__/__snapshots__/buscas-realizadas.test.js.snap
- pages/admin/__tests__/buscas-realizadas.test.js
- pages/admin/buscas-realizadas.vue
[Peek 2022-10-29 15-05.webm](https://user-images.githubusercontent.com/38293875/198846564-53b3b773-6cea-4ffc-8a76-d52e2ee0a0ce.webm)
> [Issue-27] - Página de buscas realizadas

- .eslintrc.js
- pages/admin/__tests__/__snapshots__/solicitacoes.test.js.snap
- pages/admin/__tests__/solicitacoes.test.js
- pages/admin/solicitacoes.vue
[Peek 10-11-2022 19-25.webm](https://user-images.githubusercontent.com/38293875/201219156-d6bb84b8-88e2-4088-a06d-c569e71873b2.webm)
> [Issue-43] - Página de Solicitações no Admin

- components/SideBar.vue
- layouts/admin.vue
[Peek 10-11-2022 19-45.webm](https://user-images.githubusercontent.com/38293875/201221966-e49838df-1b31-4ae1-b473-56abe8f7178f.webm)
> [Issue-45] - Adicionando rotas de admin na sidebar

- assets/js/adminItems.json
- components/SideBar.vue
- components/__tests__/SideBar.test.js
- components/__tests__/__snapshots__/SideBar.test.js.snap
- components/admin/TheHeader.vue
- components/admin/__tests__/TheHeader.test.js
- components/admin/__tests__/__snapshots__/TheHeader.test.js.snap
- layouts/admin.vue
> [Issue-38] - Tornando Header do admin dinâmico

- pages/index.vue
> [Issue-58] - Ajuste na altura da imagem principal

- pages/__tests__/__snapshots__/index.test.js.snap
- pages/__tests__/index.test.js
- pages/index.vue
Integra buscas realizadas com o back-end para salvá-las no banco de dados.
> [Issue-60] - calls emtu-api to save searches

- pages/__tests__/__snapshots__/solicitacao.test.js.snap
- pages/__tests__/solicitacao.test.js
- pages/solicitacao.vue
> [Issue-41] - integra página de solicitação com o back-end

- components/LoadingAbsolute.vue
- layouts/default.vue
- pages/index.vue
- store/loading.js
https://github.com/UnifespCodeLab/emtu-web/assets/66329978/ddb6c4a2-ff8a-495d-9763-eaf976031bf0
https://github.com/UnifespCodeLab/emtu-web/assets/66329978/1dc99d05-3de1-4d69-9911-072e77f43b94
> [Issue - 67] Adicionando componente de loading

- pages/__tests__/__snapshots__/rotas.test.js.snap
- pages/__tests__/index.test.js
- pages/__tests__/rotas.test.js
- pages/rotas.vue
> [Issue-79] - Implementar pontos na tela de rota

- components/GlobalAlert.vue
- layouts/admin.vue
- layouts/default.vue
- layouts/login.vue
- pages/__tests__/__snapshots__/index.test.js.snap
- pages/__tests__/__snapshots__/solicitacao.test.js.snap
- pages/__tests__/index.test.js
- pages/__tests__/solicitacao.test.js
- pages/admin/__tests__/__snapshots__/index.test.js.snap
- pages/admin/index.vue
- pages/index.vue
- pages/solicitacao.vue
- store/alert.js
Foi criado um componente global de Alert, que fica implementado nos `layouts`. 
Basta usar as `actions` da store para exibir/esconder ele nas páginas.
https://github.com/UnifespCodeLab/emtu-web/assets/32873281/ad8b6438-f2bd-40a4-9649-eeaeec584883
> [Issue 77] - Criando "Tooltip" global

- store/cid.js
> [Issue 83] - Formatando select de cids

- pages/index.vue
https://github.com/UnifespCodeLab/emtu-web/assets/66329978/519d73f0-6629-490e-a6b7-9828f8f7adfc
> [Issue - 70] Adicionando validação no formulário antes da busca

- pages/__tests__/index.test.js
- store/bus.js
Relacionado com issue da API: https://github.com/UnifespCodeLab/emtu-api/issues/57
> [Issue 57] - Removendo request /searches do front

- pages/admin/__tests__/__snapshots__/ranking-linhas.test.js.snap
- pages/admin/__tests__/ranking-linhas.test.js
- pages/admin/ranking-linhas.vue
> [Issue 95] - Admin - Ranking das linhas

- assets/js/adminItems.json
- components/__tests__/__snapshots__/SideBar.test.js.snap
- components/admin/__tests__/__snapshots__/TheHeader.test.js.snap
- pages/admin/home.vue
- pages/admin/index.vue
> [Issue-96]

- package.json
- pages/admin/__tests__/__snapshots__/solicitacoes.test.js.snap
- pages/admin/__tests__/solicitacoes.test.js
- pages/admin/solicitacoes.vue
> [Admin] Integrando dash de solicitação

- pages/__tests__/__snapshots__/sobre-nos.test.js.snap
- pages/__tests__/sobre-nos.test.js
- pages/sobre-nos.vue
feat: creation of new test for SobreNos.vue
> [Issue 110] - Criação de Teste da Página SobreNos.vue
